name: 'Image media type'
description: 'Provides "Image" media type and related configuration. Use local images for reusable media.'
type: 'Media type'
recipes:
  - core/recipes/image_media_type
install:
  - crop
  - focal_point
config:
  strict: false
  actions:
    core.entity_form_display.media.image.default:
      simpleConfigUpdate:
        content:
          field_media_image:
            type: image_focal_point
            weight: -10
            region: content
            settings:
              progress_indicator: throbber
              preview_image_style: max_1300x1300
              preview_link: true
              offsets: '50,50'
            third_party_settings: {  }
    media.type.image:
      simpleConfigUpdate:
        dependencies:
          module:
            - crop
        third_party_settings:
          crop:
            image_field: field_media_image