name: 'Normalized Responsive Images - landscape Golden Ratio (1.61803:1)'
description: 'A recipe for displaying landscape Golden Ratio (1.61803:1) responsive images using custom image view modes.'
type: 'Media type'
recipes:
  - nri_image_media_type
  - core/recipes/standard_responsive_images
install:
  - crop
  - focal_point
  - image_style_quality
config:
  strict: false
