name: 'Normalized Responsive Images - scaled (Max dimension)'
description: 'A recipe for displaying scaled (Max dimension) responsive images using custom image view modes.'
type: 'Media type'
recipes:
  - nri_image_media_type
  - core/recipes/standard_responsive_images
install:
  - crop
  - focal_point
  - image_style_quality
config:
  strict: false
